export const shopCategories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "home_living", label: "Home & Living" },
  { value: "books", label: "Books & Stationery" },
  { value: "health_beauty", label: "Health & Beauty" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "automotive", label: "Automotive & Vehicles" },
  { value: "groceries", label: "Groceries & Daily Needs" },
  { value: "furniture", label: "Furniture & Decor" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "baby_products", label: "Baby & Kids Products" },
  { value: "pet_supplies", label: "Pet Supplies & Accessories" },
  { value: "office_supplies", label: "Office & School Supplies" },
  { value: "music", label: "Musical Instruments & Audio" },
  { value: "gaming", label: "Gaming & Consoles" },
  { value: "appliances", label: "Home Appliances" },
  { value: "tools", label: "Tools & Hardware" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "footwear", label: "Footwear" },
  { value: "watches", label: "Watches & Wearables" },
  { value: "arts_crafts", label: "Arts & Crafts" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "cleaning", label: "Cleaning Supplies" },
  { value: "fitness", label: "Fitness Equipment" },
  { value: "vape", label: "Vape Products" },
  { value: "other", label: "Other" }
];